### ISSUE TITLE
Error on `zenpacklib --create` command

### ISSUE THREAD

**Issue by vikt0rs** [zenoss/ZenPacks.zenoss.ZenPackLib#415]
Hi folks,

I'm trying to create a new ZP using documentation from https://zenpack-sdk.zenoss.com/en/latest/getting-started.html but I'm getting a strange exception during the command run. Please find trace below

```[zenoss@domain ~]$ zenpacklib --create ZenPack.zenoss.PS.EMCXtremIO
Creating source directory for ZenPack.zenoss.PS.EMCXtremIO:
  - making directory: ZenPack.zenoss.PS.EMCXtremIO/ZenPack/zenoss/PS/EMCXtremIO
  - creating file: ZenPack.zenoss.PS.EMCXtremIO/setup.py
  - creating file: ZenPack.zenoss.PS.EMCXtremIO/MANIFEST.in
  - creating file: ZenPack.zenoss.PS.EMCXtremIO/ZenPacks/__init__.py
Traceback (most recent call last):
  File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.ZenPackLib-2.0.1.egg/ZenPacks/zenoss/ZenPackLib/zenpacklib.py", line 169, in <module>
    script.run()
  File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.ZenPackLib-2.0.1.egg/ZenPacks/zenoss/ZenPackLib/lib/libexec/ZPLCommand.py", line 187, in run
    self.create_zenpack_srcdir(self.options.zenpack)
  File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.ZenPackLib-2.0.1.egg/ZenPacks/zenoss/ZenPackLib/lib/libexec/ZPLCommand.py", line 287, in create_zenpack_srcdir
    with open(namespace_init_fname, 'w') as namespace_init_f:
IOError: [Errno 2] No such file or directory: 'ZenPack.zenoss.PS.EMCXtremIO/ZenPacks/__init__.py'```

```[zenoss@domain ~]$ zenpacklib --version
2.0.0dev```

**Comment by vikt0rs** [comment]
ok, the quick debug showed, that the error was in initial ZP name - `ZenPack.zenoss.PS.EMCXtremIO` not `ZenPacks.zenoss.PS.EMCXtremIO`. Should this be handled in some way?

**Comment by cluther** [comment]
@vikt0rs: Yes. Validating that the name starts with `ZenPacks.` sounds like a good idea. I had to look at the error for quite a while even after you explained what it was to realize it was a missing s.

**Comment by vikt0rs** [comment]
@cluther ok, I'll prepare a PR to handle this situation, if nobody minds
